### ISSUE TITLE
make: *** [test] Error 1

### ISSUE THREAD

**Issue by fabrandolini** [evilsocket/arminject#12]
Any idea about this error I'm getting with "make test"?

`MacBook-Pro-Bran:arminject-master bran$ make test
[armeabi-v7a] Compile++ thumb: hook <= main.cpp
[armeabi-v7a] Compile++ thumb: hook <= hook.cpp
[armeabi-v7a] Compile++ thumb: hook <= report.cpp
[armeabi-v7a] Compile++ thumb: hook <= io.cpp
[armeabi-v7a] SharedLibrary  : libhook.so
[armeabi-v7a] Install        : libhook.so => libs/armeabi-v7a/libhook.so
[armeabi-v7a] Compile++ thumb: injector <= main.cpp
[armeabi-v7a] Executable     : injector
[armeabi-v7a] Install        : injector => libs/armeabi-v7a/injector
python test.py
@ Pushing files to /data/local/tmp ...
adb I  2522 14384 usb_osx.cpp:259] Found vid=22b8 pid=2e76 serial=ZX1B24GXK3
adb I  2522 14384 usb_osx.cpp:259] 

@ Starting com.android.chrome/com.google.android.apps.chrome.Main ...
Traceback (most recent call last):
  File "test.py", line 48, in <module>
    pid = adb.start_activity( process, activity )
  File "/Users/bran/Documents/arminject-master/pyadb/adb.py", line 63, in start_activity
    return self.get_pid( proc )
  File "/Users/bran/Documents/arminject-master/pyadb/adb.py", line 57, in get_pid
    return int( self.sudo( "pidof %s" % proc ).strip() )
ValueError: invalid literal for int() with base 10: ''
make: **\* [test] Error 1`

**Comment by maqsoodahmadjan** [comment]
Make sure you have linux tools installed on your mobile device. You can do that using BusyBox.

**Comment by mokhdzanifaeq** [comment]
or you can try replace this line

```
return int( self.sudo( "pidof %s" % proc ).strip() )
```

into this

```
return int( self.sh('set `ps|grep %s`; echo $2' % proc).strip() )
```

in pyadb/adb.py

**Comment by snapmaster** [comment]
Same problem. Linux tools does not help.. @fabrandolini how do u solved it?
